# -*- coding: utf-8 -*-
"""ForestFire.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lK8vU518-R83XHChWPG09Wkzr6q3kGfx
"""

!curl -L "https://public.roboflow.com/ds/PsWjReQjwO?key=kLPYUljQ2X" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/ultralytics/yolov5.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5/
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cat /content/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /
from glob import glob

train_img_list = glob('/content/train/images/*.jpg')

print(len(train_img_list))

# Commented out IPython magic to ensure Python compatibility.
# %cd /
from glob import glob

test_img_list = glob('/content/test/images/*.jpg')

print(len(test_img_list))

# Commented out IPython magic to ensure Python compatibility.
# %cd /
from glob import glob

valid_img_list = glob('/content/valid/images/*.jpg')

print(len(valid_img_list))

with open('/content/train.txt','w') as f:
  f.write('\n'.join(train_img_list)+'\n')

with open('/content/valid.txt','w') as f:
  f.write('\n'.join(valid_img_list)+'\n')

import yaml

with open('/content/data.yaml','r') as f:
  data = yaml.load(f)

# 원래 파일
print(data)

data['train'] = '/content/train.txt'
data['val'] = '/content/valid.txt'

with open('/content/data.yaml','w') as f:
  yaml.dump(data, f)

# 바뀐 파일
print(data)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5/

!python train.py --img 640 --batch 16 --epochs 30 --data /content/data.yaml --cfg ./models/yolov5s.yaml --weights yolov5s.pt --name forestfire_yolov5s_results

from IPython.display import Image
import os

val_img_path = valid_img_list[5]

!python detect.py --weights /content/yolov5/runs/train/forestfire_yolov5s_results/weights/best.pt --img 640 --conf 0.5 --source "{val_img_path}"

from IPython.display import YouTubeVideo, display
video = YouTubeVideo("wItE6dM54Vc",width=500)
display(video)

!sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
!sudo chmod a+rx /usr/local/bin/youtube-dl

!pip install youtube-dl 
!youtube-dl -f mp4 https://www.youtube.com/watch?v=wItE6dM54Vc&ab_channel=DroneCenter 22

val_img_path = """/content/yolov5/항공촬영 - 낭월동 산불 (리얼영상)-wItE6dM54Vc.mp4"""

!python detect.py --weights '/content/yolov5/runs/train/forestfire_yolov5s_results/weights/best.pt' --img 640 --conf 0.5 --source "{val_img_path}"

